dist: xenial

addons:
  apt:
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazelisk/releases/download/v1.14.0/bazelisk-linux-amd64
  - mv bazelisk-linux-amd64 bazel
  - export $PATH:$(pwd)

script:
  - bazel version