name: Deploy to AWS
on:
  workflow_run:
    workflows: ["TESTS"]
    types:
      - completed
    branches:
      - main

jobs:
  push_aws:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - uses: actions/checkout@v3
      - name: Push to AWS
        run: |
          cd ${GITHUB_WORKSPACE}/ci/deploy; ./deploy.sh
