name: Deploy to AWS
on:
  workflow_run:
    workflows: ["TESTS"]
    types:
      - completed
    branches:
      - main

jobs:
  push_aws:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: actions/checkout@v3
      - name: Push to AWS
        run: |
          cd ${GITHUB_WORKSPACE}/ci/deploy/backend
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_DOCKER_REPO=${{ secrets.AWS_DOCKER_REPO }}
          export AWS_CLUSTER=${{ secrets.AWS_CLUSTER }}
          export AWS_SERVICE=${{ secrets.AWS_SERVICE }}
          export AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}
          ./deploy.sh
