name: BZL
on:
  push: {}

jobs:
  install_bazel:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Bazelisk
      run: |
        wget https://github.com/bazelbuild/bazelisk/releases/download/v1.14.0/bazelisk-linux-amd64
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
    
    - name: Check Version
      run: |
        bazel version