name: LINTERS

on:
  push

jobs:  
  run_linters:
    runs-on: ubuntu-latest

    steps:
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Mount cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      
      - uses: actions/checkout@v3
      
      - name: Run Black Linter
        run: |
          bazel run //ci:lint_black -- --check ${GITHUB_WORKSPACE}/shortlist

      - name: Run Flake8
        run: |
          bazel run //ci:lint_flake8 -- ${GITHUB_WORKSPACE}/shortlist