name: TEST_BAZEL

on:
  push

jobs:  
  print_version:
    runs-on: ubuntu-latest

    steps:
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Mount cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      - name: Test Version
        run: |
          bazel version