name: TESTS

on:
  push

jobs:
  run_tests:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Mount cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: actions/checkout@v3

      # These still require fucking open RDS connections
      
      - name: Django Tests
        run:
          bazel run //ci/testing:django -- --output_dir=${GITHUB_WORKSPACE}/ci/testing/
      
      - name: Update Coverage
        run:
          cd ${GITHUB_WORKSPACE}/coverage; COVERALLS_REPO_TOKEN=${{secrets.COVERALL_TOKEN}} coveralls
